"""
cadi_saml.simulation.plugins.calculix

CalculiX FEA (.inp) Solver Input File Exporter:
- Formats tetrahedral structural mesh (nodes and elements) into standard Abaqus/CalculiX .inp
- Defines material cards (*MATERIAL, *ELASTIC, *DENSITY)
- Sets up fixed boundary conditions (*BOUNDARY) and point/pressure loads (*CLOAD, *DLOAD)
- Writes execution steps for static stress or modal eigenvalue extraction
"""

from __future__ import annotations

import os
from typing import Dict, List, Optional, Tuple, Any
import numpy as np


class CalculiXInputExporter:
    """
    Exports CADi SAML FEA studies to CalculiX/Abaqus compatible .inp decks.
    """

    def __init__(
        self,
        job_name: str = "cad_analysis",
        youngs_modulus_mpa: float = 210000.0,
        poissons_ratio: float = 0.3,
        density_kg_mm3: float = 7.85e-6,
    ):
        self.job_name = job_name
        self.youngs_modulus = youngs_modulus_mpa
        self.poissons_ratio = poissons_ratio
        self.density = density_kg_mm3

    def generate_inp_content(
        self,
        nodes: np.ndarray,      # shape (N, 3)
        elements: np.ndarray,   # shape (M, 4) 1-based or 0-based tet indices
        fixed_node_ids: List[int],  # 1-based node IDs
        loaded_nodes_forces: Dict[int, Tuple[float, float, float]], # {node_id: (Fx, Fy, Fz)} in Newtons
        analysis_type: str = "static",  # 'static' or 'modal'
        num_modes: int = 6,
    ) -> str:
        """
        Synthesizes complete standard CalculiX deck.
        """
        lines = [
            f"** CalculiX Input Deck Generated by CADi SAML",
            f"*HEADING",
            f"{self.job_name} - CADi SAML Automated Structural Analysis",
            f"** -------------------------------------------------------------",
            f"** NODE DEFINITIONS",
            f"*NODE, NSET=NALL",
        ]

        # 1. Nodes (1-indexed)
        for i, pt in enumerate(nodes):
            nid = i + 1
            lines.append(f"{nid}, {pt[0]:.6f}, {pt[1]:.6f}, {pt[2]:.6f}")

        # 2. Elements (C3D4 4-node tetrahedral elements)
        lines.append("** -------------------------------------------------------------")
        lines.append("** ELEMENT DEFINITIONS (C3D4 Tetrahedra)")
        lines.append("*ELEMENT, TYPE=C3D4, ELSET=EBODY")
        for j, elem in enumerate(elements):
            eid = j + 1
            # ensure 1-based indexing for CalculiX
            n1 = int(elem[0]) + 1 if np.min(elements) == 0 else int(elem[0])
            n2 = int(elem[1]) + 1 if np.min(elements) == 0 else int(elem[1])
            n3 = int(elem[2]) + 1 if np.min(elements) == 0 else int(elem[2])
            n4 = int(elem[3]) + 1 if np.min(elements) == 0 else int(elem[3])
            lines.append(f"{eid}, {n1}, {n2}, {n3}, {n4}")

        # 3. Material and Section
        lines.extend([
            "** -------------------------------------------------------------",
            "** MATERIAL PROPERTIES",
            "*MATERIAL, NAME=STRUCT_MAT",
            "*ELASTIC",
            f"{self.youngs_modulus:.2f}, {self.poissons_ratio:.3f}",
            "*DENSITY",
            f"{self.density:.6e}",
            "*SOLID SECTION, ELSET=EBODY, MATERIAL=STRUCT_MAT",
        ])

        # 4. Step Definition
        lines.extend([
            "** -------------------------------------------------------------",
            "** ANALYSIS STEP",
            "*STEP",
        ])

        if analysis_type.lower() == "modal":
            lines.extend([
                "*FREQUENCY",
                f"{num_modes}",
            ])
        else:
            lines.extend([
                "*STATIC",
            ])

        # 5. Boundary Conditions (Fixed Nodes)
        if fixed_node_ids:
            lines.extend([
                "** FIXED BOUNDARY CONSTRAINTS",
                "*BOUNDARY",
            ])
            for nid in fixed_node_ids:
                lines.append(f"{nid}, 1, 3, 0.0")

        # 6. Concentrated Loads
        if loaded_nodes_forces and analysis_type.lower() != "modal":
            lines.extend([
                "** APPLIED MECHANICAL LOADS",
                "*CLOAD",
            ])
            for nid, (fx, fy, fz) in loaded_nodes_forces.items():
                if abs(fx) > 1e-4:
                    lines.append(f"{nid}, 1, {fx:.4f}")
                if abs(fy) > 1e-4:
                    lines.append(f"{nid}, 2, {fy:.4f}")
                if abs(fz) > 1e-4:
                    lines.append(f"{nid}, 3, {fz:.4f}")

        # 7. Output Requests
        lines.extend([
            "** OUTPUT VARIABLES (Displacements U, Stresses S)",
            "*NODE FILE",
            "U",
            "*EL FILE",
            "S",
            "*END STEP",
        ])

        return "\n".join(lines) + "\n"

    def export_inp(
        self,
        filepath: str,
        nodes: np.ndarray,
        elements: np.ndarray,
        fixed_node_ids: List[int],
        loaded_nodes_forces: Dict[int, Tuple[float, float, float]],
        analysis_type: str = "static",
        num_modes: int = 6,
    ) -> str:
        """Writes .inp deck to disk and returns the absolute path."""
        os.makedirs(os.path.dirname(os.path.abspath(filepath)), exist_ok=True)
        content = self.generate_inp_content(
            nodes=nodes,
            elements=elements,
            fixed_node_ids=fixed_node_ids,
            loaded_nodes_forces=loaded_nodes_forces,
            analysis_type=analysis_type,
            num_modes=num_modes,
        )
        with open(filepath, "w", encoding="utf-8") as f:
            f.write(content)
        return os.path.abspath(filepath)
